import type { Metadata } from "next";
import { v2 as cloudinary } from "cloudinary";
import { notFound } from "next/navigation";
import { APP_URL } from "@/lib/constants";
import { makeCaption, makeXIntent } from "@/lib/share";

async function getShare(id:string){
 if(!process.env.CLOUDINARY_CLOUD_NAME||!process.env.CLOUDINARY_API_KEY||!process.env.CLOUDINARY_API_SECRET)return null;
 cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET,secure:true});
 try{return await cloudinary.api.resource(`frame-goa-2026/${id}`,{resource_type:"image",context:true});}catch{return null;}
}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const resource=await getShare(id);if(!resource)return {title:"FRAME/GOA — Builder ID"};const c=resource.context?.custom||{};return {title:`${c.name||"Builder"} — ${c.title||"Builder Identity"}`,description:`${c.name||"Builder"} is ${c.title||"a builder"} at Hacker House Goa 2026. #FrameInGoa`,openGraph:{title:`${c.name||"Builder"} — ${c.title||"Builder Identity"}`,description:`${c.stack||"Builder"} · Hacker House Goa 2026`,images:[resource.secure_url]},twitter:{card:"summary_large_image",title:`${c.name||"Builder"} — ${c.title||"Builder Identity"}`,description:`${c.stack||"Builder"} · Hacker House Goa 2026`,images:[resource.secure_url]}}}
export default async function SharePage({params}:{params:Promise<{id:string}>}){const {id}=await params;const resource=await getShare(id);if(!resource)notFound();const c=resource.context?.custom||{};const caption=makeCaption({stack:c.stack||"Builder",title:c.title||"THE BUILDING MACHINE"},`${APP_URL}/share/${id}`);return <main className="min-h-screen bg-[var(--green)] px-5 py-10 text-[var(--cream)]"><div className="mx-auto max-w-5xl"><div className="mb-7 flex items-center justify-between"><div className="font-black tracking-[.2em]">HACKER HOUSE GOA · 2026</div><div className="rounded-full bg-[var(--yellow)] px-4 py-2 text-xs font-black text-black">#FrameInGoa</div></div><div className="grid items-center gap-8 lg:grid-cols-[1fr_.7fr]"><div className="overflow-hidden rounded-[1.5rem] shadow-[12px_12px_0_var(--pink)]"><img src={resource.secure_url} alt={`Builder ID for ${c.name||"builder"}`} className="block w-full"/></div><div><div className="text-sm font-black tracking-[.2em] text-[var(--yellow)]">BUILDER IDENTITY</div><h1 className="mt-3 font-display text-5xl font-black leading-[.9]">{c.name||"BUILDER"}</h1><p className="mt-4 text-xl font-bold text-white/70">{c.title||"THE BUILDING MACHINE"}</p><a href={makeXIntent(caption)} target="_blank" rel="noreferrer" className="mt-8 flex w-fit rounded-full bg-[var(--pink)] px-6 py-4 font-black text-white">SHARE TO X ↗</a><p className="mt-5 text-xs leading-relaxed text-white/45">{caption}</p></div></div></div></main>}
